Repository radiopanel/radiopanel, pull requests merged in 2021-06, with the labels that each got.

#28 chore: update README
  README.md
Labels: documentation

#30 fix: authentication method create ui
  app/src/app/authentication-method/pages/create/create.page.html
  app/src/app/authentication-method/pages/detail/detail.page.html
Labels: bug

#31 feat: add scheduling content
  api/package-lock.json
  api/package.json
  api/src/database/entities/content.entity.ts
  api/src/database/entities/page.entity.ts
  api/src/database/migrations/1623428655107-AddPublishTimingToEntity.ts
  api/src/modules/content/services/content.service.ts
  api/src/modules/shared/webhooks.ts
  app/src/app/content/pages/content-create/content-create.page.html
  app/src/app/content/pages/content-create/content-create.page.ts
  app/src/app/content/pages/content-detail/content-detail.page.html
  app/src/app/content/pages/content-detail/content-detail.page.ts
  app/src/app/content/pages/content-list/content-list.page.html
  app/src/assets/scss/atoms/a-badge.scss
  app/src/assets/scss/atoms/a-dot.scss
  app/src/assets/scss/atoms/a-input.scss
  app/src/assets/scss/main.scss
  app/src/assets/scss/molecules/m-tab.scss
  app/src/assets/scss/quarks/_layout.scss
  app/src/lib/ui/components/date-input/date-input.component.html
  app/src/lib/ui/components/date-input/date-input.component.ts
Labels: enhancement

#37 feat(text-input): add type
  api/src/modules/content/controllers/content-type-field.controller.ts
  app/src/lib/ui/components/dynamic-input/dynamic-input.component.html
  app/src/lib/ui/components/field-config/field-config.component.html
  app/src/lib/ui/components/text-input/text-input.component.html
Labels: enhancement

#38 feat: add email customisation
  api/src/mail/templates/passwordReset.ts
  api/src/mail/templates/registrationInvite.ts
  api/src/mail/templates/tenantInvite.ts
  api/src/modules/auth/services/password-reset.service.ts
  api/src/modules/shared/helpers/MailHelper.ts
  api/src/modules/user/services/invite.service.ts
  app/src/app/tenant/pages/index.ts
  app/src/app/tenant/pages/settings/sections/email/email.page.html
  app/src/app/tenant/pages/settings/sections/email/email.page.ts
  app/src/app/tenant/pages/settings/settings.page.html
  app/src/app/tenant/tenant-routing.module.ts
  app/src/assets/scss/main.scss
  app/src/assets/scss/organisms/o-email-preview.scss
Labels: enhancement

#41 fix(timetable): dont allow outside range
  api/src/mail/templates/registrationInvite.ts
  app/src/app/timetable/modals/event/event.modal.html
  app/src/app/timetable/modals/event/event.modal.ts
  app/src/app/timetable/pages/timetable/timetable.page.ts
  app/src/assets/scss/organisms/o-email-preview.scss
  app/src/lib/ui/components/time-input/time-input.component.html
  app/src/lib/ui/components/time-input/time-input.component.ts
Labels: bug
